################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Binary Sensor
    ################################################
    # ISY-994 door sensor component converts the
    # heartbeat into a low battery by going high
    # when the hearbeat is missed
    binary_sensor.house_front_door_sensor:
      friendly_name: "House Front Door"
      device_class: door
    binary_sensor.house_front_door_sensor_hb:
      friendly_name: "House Front Door Sensor Battery"
      device_class: battery
    binary_sensor.house_back_door_sensor:
      friendly_name: "House Back Door"
      device_class: door
    binary_sensor.house_back_door_sensor_hb:
      friendly_name: "House Back Door Sensor Battery"
      device_class: battery
    binary_sensor.garage_door_sensor:
      friendly_name: "Garage Door"
      device_class: door
    binary_sensor.garage_door_sensor_hb:
      friendly_name: "Garage Door Sensor Battery"
      device_class: battery

################################################################
## Automation
################################################################
automation:
  - alias: "House Front Door Sensor Low Battery"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: binary_sensor.house_front_door_sensor_hb
        to: "on"
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in House Front Door Sensor."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in House Front Door Sensor."

  - alias: "House Back Door Sensor Low Battery"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: binary_sensor.house_back_door_sensor_hb
        to: "on"
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in House Back Door Sensor."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in House Back Door Sensor."

  - alias: "Studio Front Door Sensor Low Battery"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: binary_sensor.studio_front_door_sensor_hb
        to: "on"
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in Studio Front Door Sensor."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in Studio Front Door Sensor."

  - alias: "Garage Door Sensor Low Battery"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_door_sensor_hb
        to: "on"
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in Garage Door Sensor."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in Garage Door Sensor."
