################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.house_front_door_sensor:
      friendly_name: "House Front Door"
      device_class: door
    binary_sensor.house_front_door_sensor_hb:
      friendly_name: "House Front Door Sensor Low Battery"
      device_class: battery
    binary_sensor.house_back_door_sensor:
      friendly_name: "House Back Door"
      device_class: door
    binary_sensor.house_back_door_sensor_hb:
      friendly_name: "House Back Door Sensor Low Battery"
      device_class: battery
    binary_sensor.studio_front_door_sensor:
      friendly_name: "Studio Front Door"
      device_class: door
    binary_sensor.studio_front_door_sensor_hb:
      friendly_name: "Studio Front Door Sensor Low Battery"
      device_class: battery
    binary_sensor.garage_door_sensor:
      friendly_name: "Garage Door"
      device_class: door
    binary_sensor.garage_door_sensor_hb:
      friendly_name: "Garage Door Sensor Low Battery"
      device_class: battery

################################################################
## Group
################################################################
group:
  door_sensors:
    name: Door Sensors
    control: hidden
    entities:
      - binary_sensor.house_front_door_sensor
      - binary_sensor.house_back_door_sensor
      - binary_sensor.studio_front_door_sensor
      - binary_sensor.garage_door_sensor
      - binary_sensor.house_front_door_sensor_hb
      - binary_sensor.house_back_door_sensor_hb
      - binary_sensor.studio_front_door_sensor_hb
      - binary_sensor.garage_door_sensor_hb

################################################################
## Alert
################################################################
alert:
  house_front_door_sensor_low_battery:
    name: "House Front Door Sensor Low Battery!"
    entity_id: binary_sensor.house_front_door_sensor_hb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  house_back_door_sensor_low_battery:
    name: "House Back Door Sensor Low Battery!"
    entity_id: binary_sensor.house_back_door_sensor_hb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  studio_front_door_sensor_low_battery:
    name: "Studio Front Door Sensor Low Battery!"
    entity_id: binary_sensor.studio_front_door_sensor_hb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  garage_door_sensor_low_battery:
    name: "Garage Door Sensor Low Battery!"
    entity_id: binary_sensor.garage_door_sensor_hb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios

################################################################
## Automation
################################################################
automation:
  - alias: "House Front Door Sensor Low Battery"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.house_front_door_sensor_hb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in House Front Door Sensor.'
          title: "Low Battery Detected"

  - alias: "House Back Door Sensor Low Battery"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.house_back_door_sensor_hb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in House Back Door Sensor.'
          title: "Low Battery Detected"

  - alias: "Studio Front Door Sensor Low Battery"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.studio_front_door_sensor_hb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Studio Front Door Sensor.'
          title: "Low Battery Detected"

  - alias: "Garage Door Sensor Low Battery"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_door_sensor_hb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Garage Door Sensor.'
          title: "Low Battery Detected"
