################################################################
## Packages / Hass
##   Startup initiaization and general.
################################################################

################################################################
## Automation
################################################################
automation:
  # Home Assistant Update available notification
  - id: ha_update_notifications
    alias: HASS update notifications
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: notify.ios_mike_iphone_ios
        data:
          message: 'There is a new Home Assistant release available.'