################################################################
## Packages / Hass
##   Startup initiaization and general.
################################################################

################################################################
## Automation
################################################################
automation:
  # Home Assistant Update available notification
  - id: ha_update_notifications
    alias: HASS update notifications
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: 'off'
        to: 'on'
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Home Assistant"
          message: "There is a new Home Assistant release available."
      - service: persistent_notification.create
        data_template:
          title: "Home Assistant"
          message: "There is a new Home Assistant release available."
