################################################################
## Packages / House
##   House ISY-994 lights, switches, and scenes
##   House Media Players
##   House Groups
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.family_room:
      friendly_name: "DirecTV Family Room"
    media_player.master_bed:
      friendly_name: "DirecTV Master Bedroom"
    media_player.apple_tv_family_room:
      friendly_name: "Apple TV Family Room"
    media_player.sonos_family_rm:
      friendly_name: "Sonos Family Room"

    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.house_back_door_sensor:
      friendly_name: "Back Door"
      device_class: door
    binary_sensor.house_front_door_sensor:
      friendly_name: "Front Door"
      device_class: door

    ################################################
    ## Light
    ################################################
    light.down_bath_light:
      friendly_name: "Downstairs Bathroom Light"
    light.family_room_fan_light:
      friendly_name: "Family Room Light"
    light.stairs_light_downstairs:
      friendly_name: "Stairs Light"
    light.utility_room_light_backdoor:
      friendly_name: "Utility Room Light"
    light.up_bath_light_door:
      friendly_name: "Upstairs Bathroom Light"
    light.up_sm_bed_closet_light:
      friendly_name: "Mikey Closet Light"

    ################################################
    ## Switch
    ################################################
    switch.computer_room_light:
      friendly_name: "Computer Room Light"
      icon: mdi:lightbulb
    switch.family_room_light:
      friendly_name: "Family Room Light"
      icon: mdi:lightbulb
    switch.family_room_movie:
      friendly_name: "Family Room Movie Mode"
      icon: mdi:movie-roll
    switch.down_bath_vent_fan:
      friendly_name: "Downstairs Bathroom Vent Fan"
      icon: mdi:fan
    switch.up_sm_bed_light:
      friendly_name: "Mikey Bedroom Light"
      icon: mdi:lightbulb
    switch.up_lg_bed_light:
      friendly_name: "Bryan Bedroom Light"
      icon: mdi:lightbulb

    ################################################
    ## Fan
    ################################################
    fan.family_room_fan:
      friendly_name: "Family Room Fan"
    fan.computer_room_fan:
      friendly_name: "Computer Room Fan"
    fan.up_lg_bed_fan:
      friendly_name: "Bryan Bedroom Fan"
    fan.up_sm_bed_fan:
      friendly_name: "Mikey Bedroom Fan"

    ################################################
    ## Remote
    ################################################
    remote.family_room:
      friendly_name: "Family Room Harmony Remote"

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Downstairs AC has been cooling yesterday
  - platform: history_stats
    name: Downstairs Cool Hours Yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Downstairs AC has been heating yesterday
  - platform: history_stats
    name: Downstairs Heat Hours Yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Upstairs AC has been cooling yesterday
  - platform: history_stats
    name: Upstairs Cool Hours Yesterday
    entity_id: sensor.upstairs_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Upstairs AC has been heating yesterday
  - platform: history_stats
    name: Upstairs Heat Hours Yesterday
    entity_id: sensor.upstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

################################################################
## Scene
################################################################
scene:
  - name: "Family Room Movie"
    entities:
      switch.family_room_movie: on    # ISY-994 scene
