################################################################
## Packages / House
##   House ISY-994 lights, switches, and scenes
##   House Media Players
##   House Groups
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.family_room:
      friendly_name: "DirecTV Family Room"
    media_player.apple_tv_family_room:
      friendly_name: "Apple TV Family Room"
    media_player.sonos_family_rm:
      friendly_name: "Sonos Family Room"

    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.house_back_door_sensor:
      friendly_name: "Back Door"
      device_class: door
    binary_sensor.house_front_door_sensor:
      friendly_name: "Front Door"
      device_class: door

    ################################################
    ## Light
    ################################################
    light.down_bath_light:
      friendly_name: "Downstairs Bathroom Light"
    light.family_room_fan_light:
      friendly_name: "Family Room Light"
    light.stairs_light_downstairs:
      friendly_name: "Stairs Light"
    light.utility_room_light_backdoor:
      friendly_name: "Utility Room Light"
    light.up_bath_light_door:
      friendly_name: "Upstairs Bathroom Light"
    light.up_sm_bed_closet_light:
      friendly_name: "Mikey Closet Light"

    ################################################
    ## Switch
    ################################################
    switch.computer_room_light:
      friendly_name: "Computer Room Light"
      icon: mdi:lightbulb
    switch.family_room_light:
      friendly_name: "Family Room Light"
      icon: mdi:lightbulb
    switch.down_bath_vent_fan:
      friendly_name: "Downstairs Bathroom Fan"
      icon: mdi:fan
    switch.up_sm_bed_light:
      friendly_name: "Mikey Bedroom Light"
      icon: mdi:lightbulb
    switch.up_lg_bed_light:
      friendly_name: "Bryan Bedroom Light"
      icon: mdi:lightbulb

    ################################################
    ## Fan
    ################################################
    fan.family_room_fan:
      friendly_name: "Family Room Fan"
    fan.computer_room_fan:
      friendly_name: "Computer Room Fan"
    fan.up_lg_bed_fan:
      friendly_name: "Bryan Bedroom Fan"
    fan.up_sm_bed_fan:
      friendly_name: "Mikey Bedroom Fan"

    ################################################
    ## Remote
    ################################################
    remote.family_room:
      friendly_name: "Family Room Harmony Remote"

################################################################
## Group
################################################################
group:
  # House Family Room
  family_room:
    name: Family Room
    control: hidden
    entities:
      - switch.family_room_light
      - fan.family_room_fan
      - scene.family_room_all_off

  # House Computer Room
  computer_room:
    name: Computer Room
    control: hidden
    entities:
      - switch.computer_room_light
      - fan.computer_room_fan
      - scene.computer_room_all_off

  # House Downstairs Bathroom
  downstairs_bathroom:
    name: Downstairs Bathroom
    control: hidden
    entities:
      - light.down_bath_light
      - switch.down_bath_vent_fan

  # Mikey's Bedroom
  mikey_bed_room:
    name: Mikey's Bedroom
    control: hidden
    entities:
      - switch.up_sm_bed_light
      - light.up_sm_bed_closet_light
      - fan.up_sm_bed_fan

  # Bryan's Bedroom
  bryan_bed_room:
    name: Bryan's Bedroom
    control: hidden
    entities:
      - switch.up_lg_bed_light
      - fan.up_lg_bed_fan

  # House Utility Room
  utility_room:
    name: Utility Room
    control: hidden
    entities:
      - light.utility_room_light_backdoor

  # House Media Players
  family_room_media:
    name: Family Room Media
    control: hidden
    entities:
      - media_player.sonos_family_rm
      - media_player.family_room
      - media_player.apple_tv_family_room

  # House Climate group
  house_climate:
    name: House Climate
    control: hidden
    entities:
      - climate.downstairs
      - climate.upstairs
      - sensor.downstairs_cool_hours_yesterday
      - sensor.upstairs_cool_hours_yesterday
      - sensor.downstairs_heat_hours_yesterday
      - sensor.upstairs_heat_hours_yesterday

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Downstairs AC has been cooling yesterday
  - platform: history_stats
    name: Downstairs Cool Hours Yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Downstairs AC has been heating yesterday
  - platform: history_stats
    name: Downstairs Heat Hours Yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Upstairs AC has been cooling yesterday
  - platform: history_stats
    name: Upstairs Cool Hours Yesterday
    entity_id: sensor.upstairs_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Upstairs AC has been heating yesterday
  - platform: history_stats
    name: Upstairs Heat Hours Yesterday
    entity_id: sensor.upstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24
