################################################################
## Packages / House
##   House ISY-994 lights, switches, and scenes
##   House Media Players
##   House Groups
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.house_back_door_sensor:
      friendly_name: "Back Door"
      device_class: door
    binary_sensor.house_front_door_sensor:
      friendly_name: "Front Door"
      device_class: door

    ################################################
    ## Light
    ################################################
    light.down_bath_light:
      friendly_name: "Downstairs Bathroom Light"
    light.up_bath_light:
      friendly_name: "Upstairs Bathroom Light"
    light.up_lg_bed_light:
      friendly_name: "Bryan Bedroom Light"
    light.up_sm_bed_light:
      friendly_name: "Mikey Bedroom Light"
    light.up_sm_bed_closet_light:
      friendly_name: "Mikey Closet Light"

    ################################################
    ## Switch
    ################################################
    switch.family_room_movie:
      friendly_name: "Movie Mode"
      icon: mdi:movie-roll
    switch.down_bath_vent_fan:
      friendly_name: "Downstairs Bathroom Vent Fan"
      icon: mdi:fan

    ################################################
    ## Fan
    ################################################
    fan.up_lg_bed_fan:
      friendly_name: "Bryan Bedroom Fan"
    fan.up_sm_bed_fan:
      friendly_name: "Mikey Bedroom Fan"

    ################################################
    ## Media Player
    ################################################
    media_player.family_room_apple_tv:
      friendly_name: "Apple TV Family Room"
    media_player.family_room:
      friendly_name: "Sonos Family Room"

    ################################################
    ## Remote
    ################################################
    remote.family_room:
      friendly_name: "Harmony Remote Family Room"

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Downstairs AC has been cooling yesterday
  - platform: history_stats
    name: Downstairs Cool Hours Yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'cool'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Downstairs AC has been heating yesterday
  - platform: history_stats
    name: Downstairs Heat Hours Yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heat'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Upstairs AC has been cooling yesterday
  - platform: history_stats
    name: Upstairs Cool Hours Yesterday
    entity_id: sensor.upstairs_thermostat_hvac_state
    state: 'cool'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Upstairs AC has been heating yesterday
  - platform: history_stats
    name: Upstairs Heat Hours Yesterday
    entity_id: sensor.upstairs_thermostat_hvac_state
    state: 'heat'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

################################################################
## Scene
################################################################
scene:
  - name: "Movie Mode"
    entities:
      switch.family_room_movie: on    # ISY-994 scene
