################################################################
## Packages / Kitchen
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Light
    ################################################
    light.kitchen_light_backdoor:
      friendly_name: "Kitchen Light"
    light.kitchen_cabinet_light_sink:
      friendly_name: "Kitchen Cabinet Lights"

    ################################################
    ## Switch
    ################################################
    switch.kitchen_lights:
      friendly_name: "Kitchen Lights"
      icon: mdi:lightbulb

    ################################################
    ## Fan
    ################################################
    fan.kitchen_fan_front:
      friendly_name: "Kitchen Fan"

    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.kitchen_multisensor_motion:
      device_class: motion

################################################################
## Group
################################################################
group:
  # House Kitchen
  kitchen:
    name: Kitchen
    control: hidden
    entities:
      - switch.kitchen_lights
      - fan.kitchen_fan_front
      - scene.kitchen_morning
      - scene.kitchen_all_off

################################################################
## Sensor
################################################################
sensor:
  - platform: template
    sensors:
      kitchen_multisensor_battery:
        friendly_name: "Kitchen Multisensor Battery"
        value_template: '{{ states.zwave.kitchen_multisensor.attributes.battery_level | default(0) }}'
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states.zwave.kitchen_multisensor.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) | int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

###############################################################
## Automation
################################################################
automation:
  - initial_state: 'on'
    alias: 'Kitchen Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.kitchen_multisensor_battery
        below: 15
      - platform: numeric_state
        entity_id: sensor.kitchen_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.kitchen_multisensor_battery
        below: 5
    action:
      service: notify.person2
      data:
        message: "Kitchen Multisensor is at {{ states('sensor.kitchen_multisensor_battery') }}% battery, it uses two CR123A batteries"
