################################################################
## Packages / Kitchen
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Switch
    ################################################
    switch.kitchen_lights:
      friendly_name: "Kitchen Lights"
      icon: mdi:lightbulb

    ################################################
    ## Fan
    ################################################
    fan.kitchen_fan_front:
      friendly_name: "Kitchen Fan"

################################################################
## Scene
################################################################
scene:
  - name: "Kitchen All Off"
    entities:
      switch.kitchen_all_off: on    # ISY-994 scene
  - name: "Kitchen Morning"
    entities:
      switch.kitchen_morning: on    # ISY-994 scene
