################################################################
## Packages / Motion
##   Handles all motion detectors
#################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.comp_room_motion_sensor_lb:
      friendly_name: "Computer Room Motion Sensor Battery"
      device_class: battery
    binary_sensor.up_bath_motion_sensor_lb:
      friendly_name: "Upstairs Bathroom Motion Sensor Battery"
      device_class: battery
    binary_sensor.up_sm_bed_motion_sensor_lb:
      friendly_name: "Upstairs Small Bedroom Motion Sensor Battery"
      device_class: battery
    binary_sensor.up_lg_bed_motion_sensor_lb:
      friendly_name: "Upstairs Large Bedroom Motion Sensor Battery"
      device_class: battery
    binary_sensor.garage_motion_sensor_lb:
      friendly_name: "Garage Motion Sensor Battery"
      device_class: battery
    binary_sensor.studio_multisensor_motion:
      device_class: motion
    binary_sensor.studio_bath_multisensor_motion:
      device_class: motion


################################################################
## Input Boolean
################################################################
input_boolean:
  # used as a state variables for motion detection
  comp_room_motion_state:
    initial: off
  up_bath_motion_state:
    initial: off
  up_sm_bed_motion_state:
    initial: off
  up_lg_bed_motion_state:
    initial: off
  garage_motion_state:
    initial: off
  spare_motion_state:
    initial: off

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: 'template'
    sensors:
      # Any motion
      any_motion:
        friendly_name: "Any Motion"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.any_house_motion', 'on')
             or is_state('binary_sensor.any_studio_motion', 'on')
             or is_state('binary_sensor.garage_motion', 'on') }}
      # Any motion in the house
      any_house_motion:
        friendly_name: "Any House Motion"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.comp_room_motion', 'on')
             or is_state('binary_sensor.comp_room_motion', 'on')
             or is_state('binary_sensor.up_bath_motion', 'on')
             or is_state('binary_sensor.up_sm_bed_motion', 'on')
             or is_state('binary_sensor.up_lg_bed_motion', 'on') }}
      # Any motion in the studio
      any_studio_motion:
        friendly_name: "Any Studio Motion"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.studio_motion', 'on') }}
      # Computer Room motion
      comp_room_motion:
        friendly_name: "Computer Room Motion"
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.comp_room_motion_state', 'on') }}
      # Upstairs Bathroom motion
      up_bath_motion:
        friendly_name: "Upstairs Bathroom Motion"
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.up_bath_motion_state', 'on') }}
      # Upstairs Small Bedroom motion
      up_sm_bed_motion:
        friendly_name: "Upstairs Small Bedroom Motion"
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.up_sm_bed_motion_state', 'on') }}
      # Upstairs Large Bedroom motion
      up_lg_bed_motion:
        friendly_name: "Upstairs Large Bedroom Motion"
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.up_lg_bed_motion_state', 'on') }}
      # Garage motion
      garage_motion:
        friendly_name: "Garage Motion"
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.garage_motion_state', 'on') }}
      # Spare Motion II
      spare_motion:
        friendly_name: "Spare Motion"
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.spare_motion_state', 'on') }}

################################################################
## Group
################################################################
group:
  house_motion:
    name: House Motion
    control: hidden
    entities:
      - binary_sensor.comp_room_motion
      - binary_sensor.master_bath_multisensor_motion
      - binary_sensor.up_bath_motion
      - binary_sensor.up_sm_bed_motion
      - binary_sensor.up_lg_bed_motion

################################################################
## Alert
################################################################
alert:
  comp_room_motion_sensor_low_battery:
    name: "Computer Room Motion Sensor Low Battery!"
    entity_id: binary_sensor.comp_room_motion_sensor_lb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  up_bath_motion_sensor_low_battery:
    name: "Upstairs Bath Motion Sensor Low Battery!"
    entity_id: binary_sensor.up_bath_motion_sensor_lb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  up_sm_bed_motion_sensor_low_battery:
    name: "Upstairs Small Bedroom Motion Sensor Low Battery!"
    entity_id: binary_sensor.up_sm_bed_motion_sensor_lb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  up_lg_bed_motion_sensor_low_battery:
    name: "Upstairs Large Bedroom Motion Sensor Low Battery!"
    entity_id: binary_sensor.up_lg_bed_motion_sensor_lb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios
  garage_motion_sensor_low_battery:
    name: "Garage Motion Sensor Low Battery!"
    entity_id: binary_sensor.garage_motion_sensor_lb
    repeat:
      - 1440
    notifiers:
      - ios_mike_iphone_ios

################################################################
## Automation
################################################################
automation:
  - alias: "Computer Room Motion Detect ON"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: binary_sensor.comp_room_motion_sensor
        control: 'DON'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.comp_room_motion_state
  - alias: "Computer Room Motion Detect OFF"
    trigger:
      platform: state
      entity_id: input_boolean.comp_room_motion_state
      from: 'off'
      to: 'on'
      for:
        minutes: 15
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.comp_room_motion_state
  - alias: "Upstairs Bath Motion Detect ON"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: binary_sensor.up_bath_motion_sensor
        control: 'DON'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.up_bath_motion_state
  - alias: "Upstairs Bath Motion Detect OFF"
    trigger:
      platform: state
      entity_id: input_boolean.up_bath_motion_state
      from: 'off'
      to: 'on'
      for:
        minutes: 15
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.up_bath_motion_state
  - alias: "Upstairs Small Bedroom Motion Detect ON"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: binary_sensor.up_sm_bed_motion_sensor
        control: 'DON'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.up_sm_bed_motion_state
  - alias: "Upstairs Small Bedroom Motion Detect OFF"
    trigger:
      platform: state
      entity_id: input_boolean.up_sm_bed_motion_state
      from: 'off'
      to: 'on'
      for:
        minutes: 15
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.up_sm_bed_motion_state
  - alias: "Upstairs Large Bedroom Motion Detect ON"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: binary_sensor.up_lg_bed_motion_sensor
        control: 'DON'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.up_lg_bed_motion_state
  - alias: "Upstairs Large Bedroom Motion Detect OFF"
    trigger:
      platform: state
      entity_id: input_boolean.up_lg_bed_motion_state
      from: 'off'
      to: 'on'
      for:
        minutes: 15
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.up_lg_bed_motion_stat
  - alias: "Garage Motion Detect ON"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: binary_sensor.garage_motion_sensor
        control: 'DON'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.garage_motion_state
  - alias: "Garage Motion Detect OFF"
    trigger:
      platform: state
      entity_id: input_boolean.garage_motion_state
      from: 'off'
      to: 'on'
      for:
        minutes: 15
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.garage_motion_state
  - alias: "Computer Room Motion Sensor Low Battery"
    #initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.comp_room_motion_sensor_lb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Computer Room Motion Sensor.'
          title: "Low Battery Detected"
  - alias: "Upstairs Bath Motion Sensor Low Battery"
    #initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.up_bath_motion_sensor_lb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Upstairs Bath Motion Sensor.'
          title: "Low Battery Detected"
  - alias: "Upstairs Small Bedroom Motion Sensor Low Battery"
    #initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.up_sm_bed_motion_sensor_lb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Upstairs Small Bedroom Motion Sensor.'
          title: "Low Battery Detected"
  - alias: "Upstairs Large Bedroom Motion Sensor Low Battery"
    #initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.up_lg_bed_motion_sensor_lb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Upstairs Large Bedroom Motion Sensor.'
          title: "Low Battery Detected"
  - alias: "Garage Motion Sensor Low Battery"
    #initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_motion_sensor_lb
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          message: 'Time to replace battery in Garage Motion Sensor.'
          title: "Low Battery Detected"
