################################################################
## Packages / Nest
## Nest Control
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Climate
    ################################################
    # climate.studio:
    #   friendly_name: "Studio Thermostat"
    climate.downstairs:
      friendly_name: "Downstairs Thermostat"
    climate.upstairs:
      friendly_name: "Upstairs Thermostat"

    ################################################
    ## Sensor
    ################################################
    sensor.downstairs_thermostat_temperature:
      friendly_name: "Downstairs Temperature"
    sensor.downstairs_thermostat_hvac_state:
      friendly_name: "Downstairs Thermostat State"
    sensor.downstairs_thermostat_operation_mode:
      friendly_name: "Downstairs Thermostat Mode"
    sensor.upstairs_thermostat_temperature:
      friendly_name: "Upstairs Temperature"
    sensor.upstairs_thermostat_hvac_state:
      friendly_name: "Upstairs Thermostat State"
    sensor.upstairs_thermostat_operation_mode:
      friendly_name: "Upstairs Thermostat Mode"

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: template
    sensors:
      downstairs_thermostat_eco:
        friendly_name: "Downstairs Thermostat Eco"
        value_template: "{{ state_attr('climate.downstairs', 'preset_mode') | lower == 'away' or state_attr('climate.downstairs', 'preset_mode') | lower == 'eco' or state_attr('climate.downstairs', 'preset_mode') | lower == 'away and eco' }}"
      upstairs_thermostat_eco:
        friendly_name: "Upstairs Thermostat Eco"
        value_template: "{{ state_attr('climate.upstairs', 'preset_mode') | lower == 'away' or state_attr('climate.upstairs', 'preset_mode') | lower == 'eco' or state_attr('climate.upstairs', 'preset_mode') | lower == 'away and eco' }}"

################################################################
## Automation
################################################################
automation:
  # Downstairs thermostat is kept in Eco mode when the following is true
  #   1. Vacation is active (binary_sensor.vacation_active == on)
  #   2. House is away (switch.house_state = off) and
  #      Guest Mode is off (input_boolean.guest_mode = off)
  - id: keep_nest_downstairs_eco
    alias: "Keep Downstairs Nest thermostat in Eco Mode"
    initial_state: "on"
    trigger:
      # Home Assistant started
      - platform: homeassistant
        event: start
      # ISY-994 House State was switched to Away
      - platform: state
        entity_id: switch.house_state
        to: "off"
      # Guest switched to inactive
      - platform: state
        entity_id: binary_sensor.guest_active
        to: "off"
      # Vacation is switched to active
      - platform: state
        entity_id: binary_sensor.vacation_active
        to: "on"
      # Downstairs Nest Thermostat switched from Eco Mode
      - platform: state
        entity_id: sensor.downstairs_thermostat_eco
        from: "on"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.vacation_active
          state: "on"
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.guest_mode
              state: "off"
            - condition: state
              entity_id: switch.house_state
              state: "off"
    action:
      - service: script.nest_downstairs_thermostat_set_eco

  # Downstairs thermostat is kept in Normal mode when the following is true
  #   1. Guest Mode is on (input_boolean.guest_mode = on)
  #   2. House is home (switch.house_state = on) and
  #      Vacation is inactive (binary_sensor.vacation_active == off)
  - id: keep_nest_downstairs_home
    alias: "Keep Downstairs Nest thermostat in Normal Mode"
    initial_state: "on"
    trigger:
      # Home Assistant started
      - platform: homeassistant
        event: start
      # ISY-994 House State was switched to Home
      - platform: state
        entity_id: switch.house_state
        to: "on"
      # Guest switched to active
      - platform: state
        entity_id: binary_sensor.guest_active
        to: "on"
      # Vacation switched to inactive
      - platform: state
        entity_id: binary_sensor.vacation_active
        to: "off"
      # Downstairs Nest Thermostat switched to Eco Mode
      - platform: state
        entity_id: sensor.downstairs_thermostat_eco
        to: "on"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: "on"
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.vacation_active
              state: "off"
            - condition: state
              entity_id: switch.house_state
              state: "on"
    action:
      - service: script.nest_downstairs_thermostat_set_home

  # Upstairs thermostat is kept in Eco mode when the following is true
  #   1. Vacation Active is on (binary_sensor.vacation_active == 'on')
  #   2. Boys Active is off (input_boolean.boys_home == 'off') and
  #   2. House is away (switch.house_state = off) and
  #      Guest Mode is off (input_boolean.guest_mode = 'off')
  - id: keep_nest_upstairs_eco
    alias: "Keep Upstairs Nest thermostat in Eco Mode"
    initial_state: "on"
    trigger:
      # Home Assistant started
      - platform: homeassistant
        event: start
      # Upstairs Nest Thermostat switched from Eco Mode
      - platform: state
        entity_id: sensor.upstairs_thermostat_eco
        to: "off"
      # ISY-994 House State was switched to Away
      - platform: state
        entity_id: switch.house_state
        to: "off"
      # Vacation Active switched to on
      - platform: state
        entity_id: binary_sensor.vacation_active
        to: "on"
      # Guest Active switched to off
      - platform: state
        entity_id: binary_sensor.guest_active
        to: "off"
      # Boys Active switched to off
      - platform: state
        entity_id: binary_sensor.boys_active
        to: "off"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.vacation_active
          state: "on"
        - condition: state
          entity_id: binary_sensor.boys_active
          state: "off"
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.guest_active
              state: "off"
            - condition: state
              entity_id: switch.house_state
              state: "off"
    action:
      - service: script.nest_upstairs_thermostat_set_eco

  # Upstairs thermostat is switched to Normal mode when the following is true
  #   1. House Assistant Started
  #   2. House State turned on (ISY-994i Home button pushed)(switch.house_state == on)
  #   3. Guest Active turned on (binary_sensor.guest_active == on)
  #   4. Vacation Active turned off (input_boolean.boys_home == 'on')
  #   5. Boys Home turned on (input_boolean.boys_home == 'on')
  - id: switch_nest_upstairs_home
    alias: "Switch Upstairs Nest thermostat to Normal Mode"
    initial_state: "on"
    trigger:
      # Home Assistant started
      - platform: homeassistant
        event: start
      # ISY-994 House State was switched to Home
      - platform: state
        entity_id: switch.house_state
        to: "on"
      # Guest Active switched to on
      - platform: state
        entity_id: binary_sensor.guest_active
        to: "on"
      # Vacation Active switched to off
      - platform: state
        entity_id: binary_sensor.vacation_active
        to: "off"
      # Boys Home switched to on
      - platform: state
        entity_id: binary_sensor.boys_active
        to: "on"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.guest_active
          state: "on"
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.vacation_active
              state: "off"
            - condition: state
              entity_id: switch.house_state
              state: "on"
    action:
      - service: script.nest_upstairs_thermostat_set_home

################################################################
## Script
################################################################
script:
  # Set Downstairs Nest thermostat to Eco mode
  nest_downstairs_thermostat_set_eco:
    alias: "Set Downstairs Nest Thermostat to Eco Mode"
    sequence:
      - service: script.turn_off
        data:
          entity_id: script.nest_downstairs_thermostat_set_home
      - delay: "00:05:00"
      - service: climate.set_preset_mode
        data_template:
          entity_id: climate.downstairs
          preset_mode: "eco"
      - service: logbook.log
        data_template:
          name: "Downstairs Thermostat"
          message: "set to Away Mode"

  # Set Downstairs Nest thermostat to Home mode
  nest_downstairs_thermostat_set_home:
    alias: "Set Downstairs Nest Thermostat to Home Mode"
    sequence:
      - service: script.turn_off
        data:
          entity_id: script.nest_downstairs_thermostat_set_eco
      - delay: "00:01:00"
      - service: climate.set_preset_mode
        data_template:
          entity_id: climate.downstairs
          preset_mode: "none"
      - service: logbook.log
        data_template:
          name: "Downstairs Thermostat"
          message: "set to Home Mode"

  # Set Upstairs Nest thermostat to Eco mode
  nest_upstairs_thermostat_set_eco:
    alias: "Set Upstairs Nest Thermostat to Eco Mode"
    sequence:
      - service: script.turn_off
        data:
          entity_id: script.nest_upstairs_thermostat_set_home
      - delay: "00:05:00"
      - service: climate.set_preset_mode
        data_template:
          entity_id: climate.upstairs
          preset_mode: "eco"
      - service: logbook.log
        data_template:
          name: "Upstairs Thermostat"
          message: "set to Away Mode"

  # Set Upstairs Nest thermostat to Home mode
  nest_upstairs_thermostat_set_home:
    alias: "Set Upstairs Nest Thermostat to Home Mode"
    sequence:
      - service: script.turn_off
        data:
          entity_id: script.nest_upstairs_thermostat_set_eco
      - delay: "00:01:00"
      - service: climate.set_preset_mode
        data_template:
          entity_id: climate.upstairs
          preset_mode: "none"
      - service: logbook.log
        data_template:
          name: "Upstairs Thermostat"
          message: "set to Home Mode"
