################################################################
## Packages / Notifications
################################################################

################################################################
## Input Booleans
################################################################
input_boolean:
  test_alerts:
    name: "Test Alerts"

################################################################
## Notify Groups
################################################################
notify:
  - name: house_alerts
    platform: group
    services:
      - service: mobile_app_mikes_iphone
      # - service: mobile_app_clara_iphone
  - name: sensor_alerts
    platform: group
    services:
      - service: mobile_app_mikes_iphone

################################################################
## Automations
################################################################
automation:
  - alias: "Turn Test Alerts off shortly after turning on"
    trigger:
      - platform: state
        entity_id: input_boolean.test_alerts
        from: "off"
        to: "on"
        for: "00:00:02"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.test_alerts
