################################################################
## Packages / Outside
##   Roof Lights, Front Gate, Septic Controller
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Cover
    ################################################
    cover.front_gate:
      friendly_name: "Front Gate"
      device_class: garage

    ################################################
    ## Switch
    ################################################
    switch.house_flood_lights_front:
      friendly_name: "House Front Flood Lights"
      icon: mdi:lightbulb
    switch.house_flood_lights_backyard:
      friendly_name: "House Backyard Flood Lights"
      icon: mdi:lightbulb
    switch.house_porch_lights_front:
      friendly_name: "House Front Porch Lights"
      icon: mdi:lightbulb
    switch.house_porch_lights_back:
      friendly_name: "House Back Porch Lights"
      icon: mdi:lightbulb
    switch.house_porch_lights_backyard:
      friendly_name: "House Backyard Porch Lights"
      icon: mdi:lightbulb
    switch.house_flood_lights:
      friendly_name: "All House Flood Lights"
      icon: mdi:lightbulb
    switch.house_porch_lights:
      friendly_name: "All House Porch Lights"
      icon: mdi:lightbulb
    switch.house_backyard_lights:
      friendly_name: "All House Backyard Lights"
      icon: mdi:lightbulb

################################################################
## Group
################################################################
group:
  # Front Gate
  front_gate:
    name: Front Gate
    control: hidden
    entities:
      - cover.front_gate

  # Frontyard ISY-994 group
  frontyard_lights:
    name: Frontyard Lights
    control: hidden
    entities:
      - switch.house_porch_lights
      - switch.house_porch_lights_front
      - switch.house_flood_lights
      - switch.house_flood_lights_front

  # Backyard ISY-994 group
  backyard_lights:
    name: Backyard Lights
    control: hidden
    entities:
      - switch.house_backyard_lights
      - switch.house_porch_lights_backyard
      - switch.house_porch_lights_back
      - switch.house_porch_lights_studio
      - switch.house_flood_lights_backyard
      - switch.house_flood_lights_front

  # Roof RGB Floodlights
  roof_floodlights:
    name: Roof Floodlights
    control: hidden
    entities:
      - input_number.roof_lights_transition_time
      - light.roof_lights
      - light.house_roof_light
      - light.studio_roof_light
      - light.garage_roof_light

  # Christmas Lights
  christmas_lights:
    name: Christmas Lights
    control: hidden
    entities:
      - input_boolean.christmas_season
      - switch.house_christmas_lights
      - switch.studio_christmas_lights

  # Septic Controller
  septic:
    name: Septic
    control: hidden
    entities:
      - sensor.septic_status
      - sensor.septic_minutes_yesterday
      - sensor.septic_usage_yesterday

##################################################
## input_number
##################################################
input_number:
  roof_lights_transition_time:
    name: "Roof Lights Transition Time"
    min: 1
    max: 300
    step: 1

##################################################
## input_boolean
##################################################
input_boolean:
  christmas_season:
    name: Christmas Lights Auto On
    icon: mdi:pine-tree

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the effluent pump is on in hours
  # time is offset to better match the pumping schedule
  - platform: history_stats
    name: "Septic Pump Hours Yesterday"
    entity_id: binary_sensor.septic_pump
    state: 'on'
    type: time
    # 3AM yesterday to 3AM this morning.
    end: '{{ now().replace(hour=3).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  - platform: template
    sensors:
      # converts the Septic Hours Yesterday minutes
      septic_minutes_yesterday:
        friendly_name: "Septic Pump Time Yesterday"
        entity_id: sensor.septic_pump_hours_yesterday
        unit_of_measurement: "m"
        value_template: '{{ states.sensor.septic_pump_hours_yesterday.state | multiply(60.0) | round(2) }}'

      # Given that it takes 27 minutes to pump out a full tank this sensor
      # provides an idea of septic usage in percent of maximum pump time
      septic_usage_yesterday:
        friendly_name: "Septic Usage Yesterday"
        entity_id: sensor.septic_pump_hours_yesterday
        unit_of_measurement: "%"
        # multiply by 60 * 100.0 / 27.0
        value_template: '{{ states.sensor.septic_pump_hours_yesterday.state | multiply(222.222222222) | round(0) }}'

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: template
    sensors:
      # Turns on when Front Gate has been open too long
      front_gate_open_too_long:
        friendly_name: "Front Gate open too long"
        delay_on: '00:04:00'
        value_template: "{{ is_state('cover.front_gate', 'open') }}"

      # Turns on when Front Gate Controller has been off the network for too long
      front_gate_controller_not_on_network:
        friendly_name: "Front Gate controller not on network"
        delay_on: '03:00:00'
        value_template: "{{ is_state('device_tracker.front_gate_controller', 'away') }}"

      # Turns on when Septic Controller has been off the network for too long
      septic_controller_not_on_network:
        friendly_name: "Septic controller not on network"
        delay_on: '03:00:00'
        value_template: "{{ is_state('device_tracker.septic_controller', 'away') }}"

      # Turns on when Septic Controller has not been Idle for too long
      septic_controller_not_idle:
        friendly_name: "Septic controller not Idle for too long"
        delay_on: '01:00:00'
        value_template: "{{ not is_state('sensor.septic_status', 'Idle') }}"

################################################################
## Automation
################################################################
automation:
  - id: roof_lights_transition_time
    alias: "Roof Lights Transition Time Send MQTT"
    trigger:
      platform: state
      entity_id: input_number.roof_lights_transition_time
    action:
      # - service: light.turn_on
      #   data_template:
      #     entity_id: "light.roof_lights"
      #     transition: "{{ trigger.to_state.state }}"
      - service: mqtt.publish
        data_template:
          topic: "hass/light/roof_lights/rgblight/set"
          payload: '{"transition": {{ trigger.to_state.state | int }}}'

  # Roof lights are turned on at just the right time after sunset
  - id: roof_lights_auto_on
    alias: "Roof Lights Automatic On"
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -5.0
    action:
      - service: light.turn_on
        entity_id: light.roof_lights

  # Roof lights go off at 2:00AM
  - id: roof_lights_auto_off
    alias: "Roof Lights Automatic Off"
    trigger:
      platform: time
      at: "02:00:00"
    action:
      - service: light.turn_off
        entity_id: light.roof_lights

  # Christmas lights are turned on at just the right time after sunset
  - id: christmas_lights_auto_on
    alias: "Christmas Lights Automatic On"
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -5.0
    condition:
      condition: state
      entity_id: input_boolean.christmas_season
      state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.house_christmas_lights
      - service: switch.turn_on
        entity_id: switch.studio_christmas_lights

  # Christmas lights go off at 2:00AM
  - id: christmas_lights_auto_off
    alias: "Christmas Lights Automatic Off"
    trigger:
      platform: time
      at: "02:00:00"
    action:
      - service: switch.turn_off
        entity_id: switch.house_christmas_lights
      - service: switch.turn_off
        entity_id: switch.studio_christmas_lights

  # turn on house back porch lights due to studio ISY994 Fast On
  - alias: "House Porch Lights Back On"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.porch_light_studio_front
        control: 'DFON'
    action:
      service: switch.turn_on
      entity_id: switch.house_porch_lights_back

  # turn off house back porch lights due to studio ISY994 Fast Off
  - alias: "House Porch Lights Back Off"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.porch_light_studio_front
        control: 'DFOF'
    action:
      service: switch.turn_off
      entity_id: switch.house_porch_lights_back

  # turn on studio front porch lights due to house ISY994 Fast On
  - alias: "Studio Porch Lights Front On"
    trigger:
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.master_bed_porch_light
          control: 'DFON'
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.back_porch_light_backdoor
          control: 'DFON'
    action:
      service: switch.turn_on
      entity_id: switch.studio_porch_lights_front

  # turn off studio front porch lights due to house ISY994 Fast Off
  - alias: "Studio Porch Lights Front Off"
    trigger:
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.master_bed_porch_light
          control: 'DFOF'
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.back_porch_light_backdoor
          control: 'DFOF'
    action:
      service: switch.turn_off
      entity_id: switch.studio_porch_lights_front

  # turn on house back flood lights due to studio ISY994 Fast On
  - alias: "House Flood Lights Back On"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.flood_light_studio_front
        control: 'DFON'
    action:
      service: switch.turn_on
      entity_id: switch.house_porch_lights_back

  # turn off house back flood lights due to studio ISY994 Fast Off
  - alias: "House Flood Lights Back Off"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.flood_light_studio_front
        control: 'DFOF'
    action:
      service: switch.turn_off
      entity_id: switch.house_porch_lights_back

  # turn on studio flood lights due to house ISY994 Fast On
  - alias: "Studio Porch Lights Front On"
    trigger:
      platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.back_porch_light_backdoor
        control: 'DFON'
    action:
      service: switch.turn_on
      entity_id: switch.studio_flood_lights

  # turn off studio flood lights due to house ISY994 Fast Off
  - alias: "Studio Porch Lights Front Off"
    trigger:
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.master_bed_porch_light
          control: 'DFOF'
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: light.studio_flood_lights
          control: 'DFOF'
    action:
      service: switch.turn_off
      entity_id: switch.studio_porch_lights_front

  # Front Gate Opened
  - id: front_gate_opened
    alias: Front Gate Opened
    trigger:
      platform: state
      entity_id: cover.front_gate
      to: 'open'
    action:
      - service: script.sonos_family_room_say
        data:
          volume: 0.7
          delay: '00:00:03'
          message: 'Front Gate Open.'
      - service: script.sonos_studio_say
        data:
          volume: 0.7
          delay: '00:00:03'
          message: 'Front Gate Open.'

  # Front Gate Open too long
  - alias: Front Gate Open too Long
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate_open_too_long
      to: 'on'
    action:
      - service: script.sonos_family_room_say
        data:
          volume: 0.7
          delay: '00:00:03'
          message: 'Front Gate Open Too Long.'
      - service: script.sonos_studio_say
        data:
          volume: 0.7
          delay: '00:00:03'
          message: 'Front Gate Open Too Long.'

################################################################
## Alert
################################################################
alert:
  # Front Gate open too long Alert
  front_gate_open_too_long:
    name: Front Gate is open too long!
    entity_id: binary_sensor.front_gate_open_too_long
    repeat:
      - 5
      - 10
      - 15
      - 30
      - 60
      - 1440
    notifiers:
      - ios_mike_iphone_ios
      - ios_clara_iphone_ios

  # Front Gate Reset Hardware occurred
  front_gate_reset_hardware_occurred:
    name: 'Front Gate Reset Hardware occurred!'
    entity_id: sensor.front_gate_status
    repeat: 1440
    state: 'Reset Hardware'
    notifiers:
      - ios_mike_iphone_ios

  # Front Gate Reset WiFi occurred
  front_gate_reset_wifi_occurred:
    name: 'Front Gate Reset WiFi occurred!'
    entity_id: sensor.front_gate_status
    repeat: 1440
    state: 'Reset WiFi Connect'
    notifiers:
      - ios_mike_iphone_ios

  # Front Gate Controller not on Network
  front_gate_controller_not_on_network:
    name: 'Front Gate controller is not on network!'
    entity_id: binary_sensor.front_gate_controller_not_on_network
    repeat:
      - 60
      - 120
      - 180
      - 720
      - 1440
    state: 'on'
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller Reset Hardware occurred
  septic_reset_hardware_occurred:
    name: 'Septic Reset Hardware occurred!'
    entity_id: sensor.septic_status
    repeat: 1440
    state: 'Reset Hardware'
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller Reset WiFi occurred
  septic_reset_wifi_occurred:
    name: 'Septic Reset WiFi occurred!'
    entity_id: sensor.septic_status
    repeat: 1440
    state: 'Reset WiFi Connect'
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller not on Network
  septic_controller_not_on_network:
    name: 'Septic controller is not on network!'
    entity_id: binary_sensor.septic_controller_not_on_network
    repeat:
      - 60
      - 120
      - 180
      - 720
      - 1440
    state: 'on'
    notifiers:
      - ios_mike_iphone_ios


  # Septic Controller not Idle for too long
  septic_controller_not_idle:
    name: "Septic controller is not 'Idle'"
    entity_id: binary_sensor.septic_controller_not_idle
    repeat:
      - 30
      - 60
      - 1400
    state: 'on'
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller override float
  septic_override_pump_occurred:
    name: 'Septic Override Pump On!'
    entity_id: sensor.septic_status
    state: 'Override Pump On'
    repeat: 5
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller has an Over Temperature Alarm Alert
  septic_overtemp_alarm_occurred:
    name: 'Septic Alarm: SSR Overtemp!'
    entity_id: sensor.septic_status
    state: 'Overtemp Alarm On'
    repeat: 5
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller has a Tank Overfull Alarm Alert
  septic_overfull_alarm_occurred:
    name: 'Septic Alarm: Tank Overfull!'
    entity_id: sensor.septic_status
    state: 'Tank High Alarm On'
    repeat:
      - 15
      - 30
      - 60
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller produced an Air Pump Alarm Alert
  septic_airpump_alarm_occurred:
    name: 'Septic Alarm: Air Pump Pressure Fail!'
    entity_id: sensor.septic_status
    state: 'Air Pump Alarm On'
    repeat: 5
    notifiers:
      - ios_mike_iphone_ios

  # Septic Controller produced a Bleach Level Alarm
  septic_bleach_alarm_occurred:
    name: 'Septic Alarm: Bleach Level Low!'
    entity_id: sensor.septic_status
    state: 'Bleach Alarm On'
    repeat: 5
    notifiers:
      - ios_mike_iphone_ios
