################################################################
## Packages / People
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Customize Person
    ################################################
    person.mike:
      entity_picture: '/local/mike.jpg'
    person.clara:
      entity_picture: '/local/clara.jpg'
    person.mikey:
      entity_picture: '/local/mikey.jpg'
    person.bryan:
      entity_picture: '/local/bryan.jpg'
    person.jim:
      entity_picture: '/local/jim.jpg'
    person.kasey:
      entity_picture: '/local/kasey.jpg'

    ################################################
    ## Customize Device Tracker
    ################################################
    device_tracker.mike_iphone:
      friendly_name: 'Mike iPhone (WiFi)'
      icon: mdi:wifi
    device_tracker.mike_iphone_ios:
      friendly_name: 'Mike iPhone (iOS)'
      icon: mdi:apple-ios
    device_tracker.mike_laptop:
      friendly_name: 'Mike Laptop (WiFi)'
      icon: mdi:wifi
    device_tracker.clara_iphone:
      friendly_name: 'Clara iPhone (WiFi)'
      icon: mdi:wifi
    device_tracker.clara_iphone_ios:
      friendly_name: 'Clara iPhone (iOS)'
      icon: mdi:apple-ios
    device_tracker.mikey_iphone:
      friendly_name: 'Mikey iPhone (WiFi)'
      icon: mdi:wifi
    device_tracker.mikey_iphone_ios:
      friendly_name: 'Mikey iPhone (iOS)'
      icon: mdi:apple-ios
    device_tracker.bryan_iphone:
      friendly_name: 'Bryan iPhone (WiFi)'
      icon: mdi:wifi
    device_tracker.bryan_iphone_ios:
      friendly_name: 'Bryan iPhone (iOS)'
      icon: mdi:apple-ios
    device_tracker.dan_iphone:
      friendly_name: 'Dan iPhone (WiFi)'
      icon: mdi:wifi
    device_tracker.jim_phone:
      friendly_name: 'Jim Android (WiFi)'
      icon: mdi:wifi
    device_tracker.kasey_phone:
      friendly_name: 'Kasey Android (WiFi)'
      icon: mdi:wifi

    ################################################
    ## Customize Group
    ################################################
    group.household:
      friendly_name: 'Household'
      icon: mdi:home

    group.guests:
      friendly_name: 'Guests'
      icon: mdi:human-male-female

    group.people_status:
      friendly_name: 'People Status'
      icon: mdi:human-male-female

    ################################################
    ## Customize Binary sensors
    ################################################
    binary_sensor.people_home:
      friendly_name: 'Somebody Home'
    binary_sensor.people_away:
      friendly_name: 'Everybody Away'

################################################################
## Group (Persons or Device Trackers only)
################################################################
group:
  # Device Trackers placed in here will be included in household status
  # Including a group of Device Trackers is also valid
  household:
    control: hidden
    entities:
      - person.mike
      - person.clara
      - person.mikey
      - person.bryan
      - person.jim
      - person.kasey

  guests:
    control: hidden
    entities:
      - device_tracker.dan_iphone

  people_status:
    control: hidden
    entities:
      - binary_sensor.people_home
      - binary_sensor.people_away
      - group.guests

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: 'template'
    sensors:
      people_home:
        entity_id:
          - group.household
        value_template: "{{ is_state('group.household', 'home') }}"
      people_away:
        entity_id:
          - binary_sensor.people_home
        value_template: "{{ is_state('binary_sensor.people_home', 'off') }}"

################################################################
## Script
################################################################
script:
  request_location_update:
    alias: "Request Location Update"
    sequence:
      - service: notify.ios_mike_iphone_ios
        data:
          message: "request_location_update"
      - service: notify.ios_clara_iphone_ios
        data:
          message: "request_location_update"
