################################################################
## Packages / Studio
##   Studio ISY-994 lights, switches, and scenes
##   Studio Media Players
##   Studio Groups and Backyard Group
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.studio_apple_tv:
      friendly_name: "Apple TV Studio"
    media_player.studio:
      friendly_name: "Sonos Studio"
    media_player.studio_bathroom:
      friendly_name: "Sonos Studio Bathroom"

    ################################################
    ## Remote
    ################################################
    remote.studio:
      friendly_name: "Harmony Remote Studio"

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: template
    sensors:
      # Studio Occupancy
      studio_presence:
        friendly_name: "Studio Occupancy"
        device_class: occupancy
        delay_off:
          minutes: 119
        value_template: >-
          {{ is_state('binary_sensor.studio_multisensor_motion', 'on') or
             is_state('binary_sensor.studio_bath_multisensor_motion', 'on') }}

################################################################
## Timer
################################################################
timer:
  studio_presence:
    duration: '02:00:00'
    
################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Studio AC was cooling yesterday
  - platform: history_stats
    name: Studio Cool Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'cool'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Studio AC was heating yesterday
  - platform: history_stats
    name: Studio Heat Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'heat'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

################################################################
## Automation
################################################################
automation:
  - alias: 'Studio Away turn off Art Mode'
    trigger:
    - platform: state
      entity_id: binary_sensor.studio_multisensor_motion
      to: 'off'
    action:
    - service: timer.start
      data:
        entity_id: timer.hallway
  
  # Studio Motion Detector Low Battery Alert
  - alias: 'Studio Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.studio_multisensor_battery
        below: 5
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Studio Multisensor is at {{ states('sensor.studio_multisensor_battery') }}% battery, it uses two CR123A batteries."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Studio Multisensor is at {{ states('sensor.studio_multisensor_battery') }}% battery, it uses two CR123A batteries."

  # Studio Attic Motion Detector Low Battery Alert
  - alias: 'Studio Attic Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_attic_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.studio_attic_multisensor_battery
        below: 5
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Studio Attic Multisensor is at {{ states('sensor.studio_attic_multisensor_battery') }}% battery, it uses one CR123A battery."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Studio Attic Multisensor is at {{ states('sensor.studio_attic_multisensor_battery') }}% battery, it uses one CR123A battery."