################################################################
## Packages / Studio Mode
##   Studio State Control
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Sensor
    ################################################
    sensor.studio_mode:
      friendly_name: "Studio Mode"

################################################################
## Input Boolean
################################################################
input_boolean:
  art_mode:
    name: "Art Mode"
    icon: mdi:ninja

################################################################
## Sensor
################################################################
sensor:
  - platform: template
    sensors:
      studio_mode:
        entity_id:
          - switch.studio_state
          - input_boolean.guest_mode
          - binary_sensor.vacation_active
        value_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            Guest
          {% elif is_state('binary_sensor.vacation_active', 'on') %}
            Vacation
          {% elif is_state('switch.studio_state', 'on') %}
            Home
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            mdi:account
          {% elif is_state('binary_sensor.vacation_active', 'on') %}
            mdi:beach
          {% elif is_state('switch.studio_state', 'on') %}
            mdi:home
          {% else %}
            mdi:home-outline
          {% endif %}

################################################################
## Automation
################################################################
automation:
  # Device Tracking switched to Nobody Home or Vacation Mode was activated
  #   Switch Studio to Away Mode if not in Guest Mode
  - id: studio_auto_away
    alias: Studio Auto Away when Nobody is Home
    trigger:
      # Nobody home
      - platform: state
        entity_id: binary_sensor.people_away
        to: "on"
        for: "00:15:00"
      # Switched to Vacation Mode
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: "on"
    # Auto Away Mode does not happen in Guest Mode
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.studio_state
      - service: logbook.log
        data_template:
          name: Studio
          message: automatically switched to Away Mode

  # Studio manually switched to Away Mode
  #   Either by HASS switch or KeypadLinc switch
  - id: studio_switched_to_away
    alias: Studio switched to Away
    trigger:
      platform: state
      entity_id: switch.studio_state
      to: "off"
    action:
      - service: logbook.log
        data_template:
          name: Studio
          message: manually switched to Away Mode
      - service: script.sonos_studio_all_say
        data:
          volume: 0.5
          delay: "00:00:02"
          message: "Goodbye."
      # turn off Studio TV
      # - service: remote.turn_off
      #   data:
      #     entity_id: remote.studio
      #     activity: PowerOff

  # Studio manually switched to Home Mode
  #   Either by HASS switch or KeypadLinc switch
  - id: studio_switched_to_home
    alias: Studio switched to Home
    trigger:
      platform: state
      entity_id: switch.studio_state
      to: "on"
    action:
      - service: logbook.log
        data_template:
          name: Studio
          message: manually switched to Home Mode
      - service: script.sonos_studio_all_say
        data:
          volume: 0.5
          delay: "00:00:02"
          message: "Hello."
