################################################################
## Packages / Studio
##   Studio ISY-994 lights, switches, and scenes
##   Studio Media Players
##   Studio Groups and Backyard Group
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.studio:
      friendly_name: "DirecTV Studio"
    media_player.apple_tv_studio:
      friendly_name: "Apple TV Studio"
    media_player.sonos_studio:
      friendly_name: "Sonos Studio"

    ################################################
    ## Fan
    ################################################
    fan.studio_fan:
      friendly_name: "Studio Fan"

    ################################################
    ## Remote
    ################################################
    remote.studio:
      friendly_name: "Studio Harmony Remote"

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: template
    sensors:
      # Studio Bath presence
      studio_presence:
        friendly_name: "Studio Someone Present"
        device_class: occupancy
        delay_off:
          minutes: 11
        value_template: >-
          {{ is_state('binary_sensor.studio_multisensor_motion', 'on') }}

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Studio AC was cooling yesterday
  - platform: history_stats
    name: Studio Cool Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Studio AC was heating yesterday
  - platform: history_stats
    name: Studio Heat Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

###############################################################
## Automation
################################################################
automation:
  # Studio Motion Detector Low Battery Alert
  - initial_state: 'on'
    alias: 'Studio Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.studio_multisensor_battery
        below: 5
    action:
      service: notify.ios_mike_iphone_ios
      data:
        message: "Studio Multisensor is at {{ states('sensor.studio_multisensor_battery') }}% battery, it uses two CR123A batteries."

  # Studio Attic Motion Detector Low Battery Alert
  - initial_state: 'on'
    alias: 'Studio Attic Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_attic_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.studio_attic_multisensor_battery
        below: 5
    action:
      service: notify.ios_mike_iphone_ios
      data:
        message: "Studio Attic Multisensor is at {{ states('sensor.studio_attic_multisensor_battery') }}% battery, it uses one CR123A batteries."
