################################################################
## Packages / Studio
##   Studio ISY-994 lights, switches, and scenes
##   Studio Media Players
##   Studio Groups and Backyard Group
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.studio_apple_tv:
      friendly_name: "Apple TV Studio"
    media_player.studio:
      friendly_name: "Sonos Studio"
    media_player.studio_bathroom:
      friendly_name: "Sonos Studio Bathroom"

    ################################################
    ## Remote
    ################################################
    remote.studio:
      friendly_name: "Harmony Remote Studio"

################################################################
## Binary Sensor
################################################################
binary_sensor:
  - platform: template
    sensors:
      # Studio Bath presence
      studio_presence:
        friendly_name: "Studio Someone Present"
        device_class: occupancy
        delay_off:
          minutes: 11
        value_template: >-
          {{ is_state('binary_sensor.studio_multisensor_motion', 'on') }}

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Studio AC was cooling yesterday
  - platform: history_stats
    name: Studio Cool Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'cool'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Studio AC was heating yesterday
  - platform: history_stats
    name: Studio Heat Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'heat'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24
