################################################################
## Packages / Studio
##   Studio ISY-994 lights, switches, and scenes
##   Studio Media Players
##   Studio Groups and Backyard Group
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.studio:
      friendly_name: "DirecTV Studio"
    media_player.apple_tv_studio:
      friendly_name: "Apple TV Studio"
    media_player.sonos_studio:
      friendly_name: "Sonos Studio"

    ################################################
    ## Fan
    ################################################
    fan.studio_fan:
      friendly_name: "Studio Fan"

    ################################################
    ## Remote
    ################################################
    remote.studio:
      friendly_name: "Studio Harmony Remote"

################################################################
## Group
################################################################
group:
  # Studio group
  studio:
    name: Studio
    control: hidden
    entities:
      - light.studio_chandeliers
      - switch.studio_shoplights
      - switch.studio_shoplight_a
      - switch.studio_shoplight_b
      - switch.studio_shoplight_c
      - switch.studio_shoplight_d
      - fan.studio_fan
      - light.studio_fan_light

  # Studio Kitchen group
  studio_kitchen:
    name: Studio Kitchen
    control: hidden
    entities:
      - switch.studio_kitchen_lights
      - light.studio_kitchen_chandelier
      - light.studio_kitchen_cabinet_lights
      - light.studio_kitchen_sink_lights

  # Studio Loft group
  studio_loft:
    name: Studio Loft
    control: hidden
    entities:
      - light.studio_loft_fan_light
      - fan.studio_loft_fan

  # Studio Media Players
  studio_media:
    name: Studio Media
    control: hidden
    entities:
      - media_player.studio
      - media_player.apple_tv_studio
      - media_player.sonos_studio

  # Studio Climate group
  studio_climate:
    name: Studio Climate
    control: hidden
    entities:
      - climate.studio
      - sensor.studio_cool_hours_yesterday
      - sensor.studio_heat_hours_yesterday

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Studio AC was cooling yesterday
  - platform: history_stats
    name: Studio Cool Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Studio AC was heating yesterday
  - platform: history_stats
    name: Studio Heat Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

###############################################################
## Automation
################################################################
automation:
  - initial_state: 'on'
    alias: 'Studio Bath Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_bath_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.studio_bath_multisensor_battery
        below: 5
    action:
      service: notify.ios_mike_iphone_ios
      data:
        message: "Studio Bath Multisensor is at {{ states('sensor.studio_bath_multisensor_battery') }}% battery, it uses two CR123A batteries."
  - initial_state: 'on'
    alias: 'Studio Attic Multisensor Low Battery'
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_attic_multisensor_battery
        below: 10
      - platform: numeric_state
        entity_id: sensor.studio_attic_multisensor_battery
        below: 5
    action:
      service: notify.ios_mike_iphone_ios
      data:
        message: "Studio Attic Multisensor is at {{ states('sensor.studio_attic_multisensor_battery') }}% battery, it uses one CR123A batteries."
