################################################################
#  Packages / weeWX
#  Davis Weather Station sensors via weeWX
################################################################

################################################
#  Customize
################################################
homeassistant:
  customize:
    ################################################
    #  Sensor
    ################################################
    sensor.weewx_temperature:
      friendly_name: "Temperature"
      icon: mdi:thermometer

    sensor.weewx_dewpoint:
      friendly_name: "Dewpoint"
      icon: mdi:thermometer

    sensor.weewx_heat_index:
      friendly_name: "Heat Index"
      icon: mdi:thermometer

    sensor.weewx_humidex:
      friendly_name: "Humidex"
      icon: mdi:thermometer

    sensor.weewx_windchill:
      friendly_name: "Windchill"
      icon: mdi:thermometer

    sensor.weewx_humidity:
      friendly_name: "Humidity"
      icon: mdi:water-percent

    sensor.weewx_barometer:
      friendly_name: "Barometer"
      icon: mdi:gauge

    sensor.weewx_wind:
      friendly_name: "Wind"
      icon: mdi:weather-windy

    sensor.weewx_wind_dir:
      friendly_name: "Dir"
      icon: mdi:crosshairs

    sensor.weewx_gust:
      friendly_name: "Gust"
      icon: mdi:weather-windy

    sensor.weewx_gust_dir:
      friendly_name: "Gust Dir"
      icon: mdi:crosshairs

    sensor.weewx_rain:
      friendly_name: "Rain"
      icon: mdi:water

    sensor.weewx_rain_rate:
      friendly_name: "Rainfall Rate"
      icon: mdi:water

    sensor.weewx_rain_storm:
      friendly_name: "Storm Rain"
      icon: mdi:water

    sensor.weewx_rain_month:
      friendly_name: "Monthly Rain"
      icon: mdi:water

    sensor.weewx_rain_year:
      friendly_name: "Yearly Rain"
      icon: mdi:water

    binary_sensor.weewx_tx_battery:
      friendly_name: "Davis ISS Battery"

################################################
#  Sensor
################################################
sensor:
  - platform: mqtt
    name: weewx_temperature
    state_topic: "weather/loop"
    unit_of_measurement: "°F"
    value_template: >
      {% if value_json.outTemp %}
        {{ value_json.outTemp | round(1) }}
      {% endif %}

  - platform: mqtt
    name: weewx_dewpoint
    state_topic: "weather/loop"
    unit_of_measurement: "°F"
    value_template: >
      {% if value_json.dewpoint %}
        {{ value_json.dewpoint | round(1) }}
      {% endif %}

  - platform: mqtt
    name: weewx_heat_index
    state_topic: "weather/loop"
    unit_of_measurement: "°F"
    value_template: >
      {% if value_json.heatindex %}
        {{ value_json.heatindex | round(1) }}
      {% endif %}

  - platform: mqtt
    name: weewx_humidex
    state_topic: "weather/loop"
    unit_of_measurement: "°F"
    value_template: >
      {% if value_json.humidex %}
        {{ value_json.humidex | round(1) }}
      {% endif %}

  - platform: mqtt
    name: weewx_windchill
    state_topic: "weather/loop"
    unit_of_measurement: "°F"
    value_template: >
      {% if value_json.windchill %}
        {{ value_json.windchill | round(1) }}
      {% endif %}

  - platform: mqtt
    name: weewx_humidity
    state_topic: "weather/loop"
    unit_of_measurement: "%"
    value_template: >
      {% if value_json.outHumidity %}
        {{ value_json.outHumidity | round(1) }}
      {% endif %}

  - platform: mqtt
    name: weewx_barometer
    state_topic: "weather/loop"
    unit_of_measurement: "in"
    value_template: >
      {% if value_json.barometer %}
        {{ value_json.barometer | round(2) }}
      {% endif %}

  - platform: mqtt
    name: weewx_wind
    state_topic: "weather/loop"
    unit_of_measurement: "mph"
    value_template: >
      {% if value_json.windSpeed %}
        {{ value_json.windSpeed | round(0) }}
      {% endif %}

  - platform: mqtt
    name: weewx_wind_dir
    state_topic: "weather/loop"
    unit_of_measurement: "°"
    value_template: >
      {% if value_json.windDir %}
        {{ value_json.windDir | round(0) }}
      {% endif %}

  - platform: mqtt
    name: weewx_gust
    state_topic: "weather/loop"
    unit_of_measurement: "mph"
    value_template: >
      {% if value_json.windGust %}
        {{ value_json.windGust | round(0) }}
      {% endif %}

  - platform: mqtt
    name: weewx_gust_dir
    state_topic: "weather/loop"
    unit_of_measurement: "°"
    value_template: >
      {% if value_json.windGustDir %}
        {{ value_json.windGustDir | round(0) }}
      {% endif %}

  - platform: mqtt
    name: weewx_rain
    state_topic: "weather/loop"
    unit_of_measurement: "in"
    value_template: >
      {% if value_json.dayRain %}
        {{ value_json.dayRain | round(2) }}
      {% endif %}

  - platform: mqtt
    name: weewx_rain_rate
    state_topic: "weather/loop"
    unit_of_measurement: "in/hr"
    value_template: >
      {% if value_json.rainRate %}
        {{ value_json.rainRate | round(2) }}
      {% endif %}

  - platform: mqtt
    name: weewx_rain_storm
    state_topic: "weather/loop"
    unit_of_measurement: "in"
    value_template: >
      {% if value_json.stormRain %}
        {{ value_json.stormRain | round(2) }}
      {% endif %}

  - platform: mqtt
    name: weewx_rain_month
    state_topic: "weather/loop"
    unit_of_measurement: "in"
    value_template: >
      {% if value_json.monthRain %}
        {{ value_json.monthRain | round(2) }}
      {% endif %}

  - platform: mqtt
    name: weewx_rain_year
    state_topic: "weather/loop"
    unit_of_measurement: "in"
    value_template: >
      {% if value_json.yearRain %}
        {{ value_json.yearRain | round(2) }}
      {% endif %}

################################################
#  Binary Sensor
################################################
binary_sensor:
  - platform: mqtt
    name: weewx_tx_battery
    state_topic: "weather/loop"
    device_class: "battery"
    value_template: >
      {%- if value_json.txBatteryStatus | default("0.0") | float == 0.0 -%}
        OFF
      {%- else -%}
        ON
      {%- endif -%}

################################################################
## Automation
################################################################
automation:
  # Septic Controller Offline for too long
  - alias: "Weather Station Battery Low"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: binary_sensor.weewx_tx_battery
        to: "on"
    action:
      - service: notify.sensor_alerts
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in Weather Station ISS."
      - service: persistent_notification.create
        data_template:
          title: "Low Battery Detected"
          message: "Time to replace battery in Weather Station ISS."
